#!/usr/bin/env python
'''
Created on Sep 5, 2012

@author: ccsplitinfinity
'''
import urllib2
import sys
import getopt
import time
import os

# Constant for the website to download the MAC address list.
OUI_WEBSITE="http://standards.ieee.org/develop/regauth/oui/oui.txt"

# Constant for where the file will be located so you don't have to
# download it everytime it is used.
OUI_FILE_LOCATION=os.environ["HOME"]+("/.config/.oui.txt")
class macresolve(): 
    def __init__(self):
        self.contents={}  
    def getOUI(self):
        print "Retrieving the remote file, could take a while..."
        ur = urllib2.urlopen(OUI_WEBSITE)
        #contents = ur.readlines()            
            
        fd = open(OUI_FILE_LOCATION, "wb")
    
        for line in ur:
            line = line.lstrip(" ")
            line = line.lstrip("\n")
            line = line.replace("(hex)","")
            line = line.replace("(base 16)","")
            if line !="":
                if not line.startswith("\t"):
                    fd.write(line.replace("-",""))
            
            line=ur.next()
        
        fd.close()

    def readOUI(self):
        fd=open(OUI_FILE_LOCATION,"rb")
        i=0
        for line in fd:
            values = line.split("\t")
            #contents+=line
            values[0]=values[0].replace(" ","")
            self.contents[values[0]]=values[2]
            i+=1

    def usage(self):
        print "*****************************************************"
        print "Usage: macresolve -a <MAC ADDRESS>"
        print "Options:"
        print "-h --help Prints out the help."
        print "-u --usage Prints out this usage."
        print "-r --refresh Will refresh the list from the website."
        print "-a --address <MAC ADDRESS> Will search for the MAC address"
        print "in the list and return the company."
        print "*****************************************************"
        
    def mac_help(self,command=None):
        if len(command)>2:
            print command[2]
            print "Boo."
            
        else:
            print "Zoboomafoo. =("
            
    def search(self,address):
        mac=sys.argv[2]
        mac=mac.replace(":","")
        mac=mac.replace("-","")
        print "*****************************************************"
        print "The company for %s is %s" % (address,self.contents[mac[0:6]])
        print "*****************************************************"
        
def main():
    # parse command line options
    program=macresolve()
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hurpa:", ["help","usage","refresh","print","address"])
    except getopt.error, msg:
        print msg
        print "for help use --help"
        sys.exit(2)
    # process options
    if len(opts)==0:
        program.usage()
    for o, a in opts:
        if o in ("-h", "--help"):
            if len(sys.argv) <2:
                program.mac_help()
                sys.exit(0)
            else:
                program.mac_help(sys.argv)
                sys.exit(0)
        if o in ("-u", "--usage"):
            program.usage()
            sys.exit(0)
        if o in ("-r", "--refresh"):
            program.getOUI()
            if len(sys.argv) == 3:
                program.search(sys.argv[2])
                sys.exit(0)
            else:
                print "Finished writing the file...exiting..."
                sys.exit(0)
        if o in ("-a","--address"):
            program.readOUI()
            program.search(sys.argv[2])
            sys.exit(0)
        
        if o in ("-p","-print"):
            print "File location: %s" % OUI_FILE_LOCATION
            
if __name__ == "__main__":
    main()